#ifndef HZ_UCD_7_0_0_H
#define HZ_UCD_7_0_0_H

#include <stdint.h>

#define HZ_UCD_VERSION HZ_MAKE_VERSION(7,0,0)

uint16_t hz_ucd_arabic_joining_k2[522] = {
       3,   0,   0,  10,   0,  16,
       0,   0,   0,  16,   6,   0,
       0,   0,   0,   1,   0,   1,
      18,   1,   0,   0,   0,   0,
       2,   0,   0,   0,   2,  11,
       0,   0,   7,   2,   0,   0,
       1,   0,   6,   0,   3,   2,
       7,   4,   2,   0,  25,  18,
       0,   3,  30,   5,  13,   2,
       3,   3,   1,   1,   9,   1,
       1,   1,   1,   7,   0,   6,
       6,   8,   0,  15,   0,   1,
      14,   1,   2,   0,   0,   1,
       3,   0,   1,   4,   0,   1,
       0,   0,   0,   1,   0,   5,
       5,   6,   1,   2,   0,   2,
       1,   3,   1,   5,   6,   1,
       0,   0,   0,   1,   4,   5,
       1,   2,   3,  12,   0,   6,
       5,   0,   1,   4,   0,   1,
       0,   2,   2,   0,   2,   0,
      16,   0,  34,   3,   0,   0,
       5,  10,   1,   1,   4,   1,
       3,   0,   2,   4,   3,   1,
       4,   0,   0,   5,   1,   0,
       7,   0,   0,   0,   1,   1,
       0,   1,   1,   0,  54,   6,
       1,   3,   0,   4,   0,   1,
       1,   1,   0,   0,   3,   2,
       1,   2,   1,   0,   0,   5,
       0,   0,   0,   2,   0,   1,
       0,   1,   0,   0,   5,   1,
       6,   0,   3,   1,   2,   0,
       2,   1,   1,  10,   2,   3,
       3,   0,   1,   1,   1,   0,
       4,   1,   8,   3,   5,   1,
       0,   1,   2,   1,   5,   0,
       3,   6,   9,   1,   9,   2,
       0,   0,   1,   0,   1,   4,
       1,   2,   0,   9,   0,  10,
       2,   3,   0,   0,   1,   0,
       3,   0,  17,   2,   1,   2,
       1,   0,   0,   4,   0,   0,
       4,   0,   6,   2,   0,   1,
      15,   0,   0,   0,  10,   9,
       2,   7,   0,  22,  14,   0,
       0,   8,   2,   1,   0,   2,
       0,  18,   1,  14,  21,   9,
       1,   0,  23,   0,  23,   0,
       0,   0,   1,   0,   5,  11,
       5,   0,   0,   0,   0,   2,
       0,  12,   0,   0,   0,   0,
       1,   2,   0,   0,   1,   2,
       1,   4, 496,  94,   0,   0,
       0,   0, 306,   0,   1,   4,
      12, 265,  11,   0,   0,   0,
       6,  71,   1,   0,  25,   7,
       0,  44,  19,  24,   2,   6,
       0,  17,   0,   0,   0,  30,
       0,   0,   7,   0,   1,  10,
       1,   0,   1,   0,   0,   1,
       0,   0,   2,   6,   3,   1,
       1,   0,   2,   1,   0,   7,
       2,   0,   2,   0,   0,   0,
       0,  14,   0,   2,  12,   4,
       0,   4,   0,   3,   2,   4,
       1,   1,   2,   4,   6,   4,
       0,   0,   0,   0,   7,   4,
       2,   0,  11,   2,   3,   0,
       2,   2,   0,   0,   2,   2,
       2,   3,   1,   7,   0,   1,
       0,   6,   1,   0,   0,   2,
       2,   0,   1,   1,   0,   2,
      15,   3,   3,   0,   0,   0,
       1,   0,   1,   2,   0,   0,
       1,   1,   1,   0,   0,   3,
       0,   2,   0,   7,   0,   4,
       2,   0,   2,   2,   9,   0,
       3,   0,   2,   2,   0,   0,
       2,   0,   3,   0,   2,  18,
       1,   6,   0,   6,  29,   0,
       1,   0,  23,   0,   5,   2,
       0,   2,   0,  22,   0,   0,
       1,   0,  12,   0,   2,   0,
       0,   1,   1,  13,   0,  28,
       1,   3,   5,   0,  21,   0,
       1,  26,  32,   0, 111, 365,
};

uint32_t hz_ucd_arabic_joining_ucs[522] = {
        1568,    6190,    1712,    1657,    1735,    1573,
        1610,    1539,    1818,    1726,    1540,    1832,
       68292,   68305,    1696,    1701,    1824,    2018,
        6237,    6196,    1895,    6307,    1590,   68303,
        1658,    1910,    1885,    1697,    1569,    6181,
        1738,    2120,    1886,    1997,    1685,    6261,
        6198,    1586,    2216,    1902,    2011,    1743,
       68324,    6256,    2112,    6194,    1881,    1710,
        2123,    6203,    1711,    1662,    6272,    1607,
        6298,    1744,    1869,    6258,    1737,    6312,
        1605,    6239,    1649,    1740,    6186,    1823,
        1774,    1757,    6235,    1585,    1999,    6222,
        6189,    8297,    1654,    2002,    1819,    1647,
        2116,    2000,    6296,    1718,    1724,    1812,
        1888,    1728,    1667,    1670,    2006,    2026,
        1687,   68316,   68311,    1600,    2121,    6293,
        1698,    1995,    1686,    6150,    6294,    1689,
        1675,    6205,    1544,    1872,    1646,    1714,
        1730,    6245,    1874,    1892,    1547,    1660,
        2016,    2025,    2130,    1896,    1836,   68315,
        2017,    1810,    6191,    1734,    2001,    1661,
        1729,    1834,    1733,    1884,    1577,    1913,
       68309,    1708,    1572,   68321,   68289,    1579,
        6182,    1741,    6208,    1787,    6249,    1680,
        1829,    1595,    6243,    1890,    1692,    1603,
        1584,    6278,    1578,    1731,   68331,    1678,
        1536,   68319,    6277,    2020,    6202,    6251,
       68493,    2013,    2015,    1599,    1749,    2005,
        1706,    1582,    2021,    1596,    1606,   68317,
        1598,    1828,    1694,    1609,    6242,    6228,
        1814,    2115,    1538,    6206,    1827,    1893,
       68295,    1815,    6244,    6299,    1688,    1537,
        1826,    6275,    1786,    2122,   68320,    1705,
        1722,   68293,    1716,    1727,    1820,    1601,
        1604,    1663,    1831,    1878,    1659,    1693,
        1775,    6229,    1915,    1671,    1699,    6308,
        1822,    1745,    1597,    1580,    2132,    1666,
        6303,    6201,   68488,    1674,    1589,    6281,
        1679,   68298,    1808,    1656,    1587,    2125,
        1702,    1898,    1676,    1672,    6255,    1887,
        6180,    1835,    1665,    1830,    1871,    1588,
        1875,    2210,   68525,    1594,    1918,    6210,
        2215,    6176,   68489,    1673,    1713,    1877,
        2004,    2118,   68484,    2225,    1575,    1652,
        6223,    6287,    2008,   68314,    2209,    1909,
        1825,    1833,    1684,   68334,    1715,    2135,
        6187,    2003,    2042,    1732,    2219,    1608,
        6285,    8205,    1677,    6305,    6226,    6158,
        6291,    6262,    1725,    6250,    6231,    6247,
        6213,   68335,    6240,    1906,    2131,    2223,
        1821,    1839,    1576,    6273,    2022,    2220,
        1900,    1583,    2024,    6204,   68333,    1704,
        6184,    6309,    2012,    6232,    1602,    1703,
        6178,    1593,    1876,    1720,    6252,    1700,
        6290,    6288,    1889,   68521,    2023,    1791,
        2222,    2014,    6306,    1695,   68332,   68496,
        6218,    1655,    1570,    1817,    2128,    1816,
        1669,    6301,    6300,    1653,    1998,    2211,
        6193,   68522,   68310,    2213,    1721,    6177,
        1719,    2218,    1883,    1683,   68483,   68526,
        1838,    1907,    1681,    2119,    6230,   68322,
        2133,    1736,    1873,    1870,    1739,    1919,
        1723,    2134,    6314,    1813,   68300,    6215,
       68294,   68490,   68296,    1903,    6179,   68301,
        6221,    6283,    1899,    1914,    1709,    1717,
       68492,    1894,    2019,    1837,    2221,    6284,
        1650,   68527,    1901,   68524,    2126,    6238,
        1788,    1690,    6257,   68482,    6297,    6216,
        1897,    6234,    1541,    1905,    2208,   68487,
        1911,    6280,   68481,    1746,   68302,   68313,
        2114,    6260,    6200,    6195,   68304,    6295,
        6311,    6246,    6302,   68312,    6241,    2007,
        1664,    1742,   68291,    6279,    1994,    1592,
       68494,    6286,    6192,    2127,    6212,    2217,
        2212,    6209,    6253,    2009,   68486,    6310,
        2226,    1707,    6154,    1682,    6199,    2129,
        1996,    2113,    6151,    6259,    6254,    6214,
        6233,    6197,    6227,    1879,    8296,   68297,
        6304,    6219,    1581,    2214,    1912,    1591,
        1904,   68299,    6211,   68288,    1668,    2224,
        1891,    1916,    6217,    1917,    2010,   68323,
       68308,   68495,    6236,    6274,    1880,    2117,
        1882,    1908,    6282,   68523,    6185,    1571,
        1811,    6207,    1651,    6276,   68318,    1574,
       68290,   68307,    1747,    6224,    6248,    2136,
        6183,    6188,   68497,    2124,   68306,    6263,
       68480,    6292,    6220,    6225,    1691,    6289,
};

uint32_t hz_ucd_arabic_joining_data[522] = {
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH SEPARATE RING BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DAMMA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH HAMZA BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SAFHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HETH << 6), /* HETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KNOTTED << 6), /* KNOTTED HEH */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SAMVAT */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_SADHE << 6), /* SADHE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN GIMEL WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAMADH << 6), /* LAMADH */
    HZ_JOINING_TYPE_D, /* NKO NYA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE E */
    HZ_JOINING_TYPE_D, /* MONGOLIAN CHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI CYA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN YODH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH */
    HZ_JOINING_TYPE_U, /* HAMZA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN OE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC ATT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* NKO E */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH V BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU RA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN YA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH BELOW */
    HZ_JOINING_TYPE_D, /* NKO SA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TAW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE RAA */
    HZ_JOINING_TYPE_R, /* MANDAIC HALQA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH VERTICAL 2 DOTS BELOW AND TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MANDAIC AL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN KHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI ANUSVARA ONE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI GHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ZHAIN << 6), /* SOGDIAN ZHAIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ZHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI BHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE IY */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WASLA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAPH << 6), /* KAPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_U, /* ARABIC END OF AYAH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO NIA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH */
    HZ_JOINING_TYPE_D, /* NKO OO */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO GA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN GA */
    HZ_JOINING_TYPE_U, /* POP DIRECTIONAL ISOLATE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* HIGH HAMZA WAW */
    HZ_JOINING_TYPE_D, /* NKO N */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TETH << 6), /* TETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF */
    HZ_JOINING_TYPE_D, /* MANDAIC AH */
    HZ_JOINING_TYPE_D, /* NKO O */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ALI GALI TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* GAMAL GARSHUNI */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* DOTLESS TEH MARBUTA WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* NKO JA */
    HZ_JOINING_TYPE_D, /* NKO JONA RA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN PE WITH DOT ABOVE */
    HZ_JOINING_TYPE_L | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN NUN */
    HZ_JOINING_TYPE_C, /* TATWEEL */
    HZ_JOINING_TYPE_R, /* MANDAIC AKSA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI ZHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* NKO EE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT BELOW AND DOT WITHIN */
    HZ_JOINING_TYPE_U, /* MONGOLIAN TODO SOFT HYPHEN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI ZA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT BELOW AND TAH ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZA */
    HZ_JOINING_TYPE_U, /* ARABIC RAY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH HORIZONTAL 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH GOAL WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE HA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* AFGHANI SIGN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH ATTACHED RING BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* NKO NA WOLOSO */
    HZ_JOINING_TYPE_D, /* NKO JONA CHA */
    HZ_JOINING_TYPE_D, /* MANDAIC AQ */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TAW << 6), /* TAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN PE */
    HZ_JOINING_TYPE_D, /* NKO MA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BETH << 6), /* BETH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN LA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* NKO DAGBASINNA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH GOAL */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* RISH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH BAR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* TEH MARBUTA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN THAMEDH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN RESH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN BETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN UE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH TAIL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN LHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE DA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_E << 6), /* E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE KA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT ABOVE */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI THREE BALUDA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* TEH MARBUTA GOAL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ONE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* ARABIC NUMBER SIGN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH WITH DOT ABOVE */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI BALUDA */
    HZ_JOINING_TYPE_D, /* NKO HA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE FA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI SAMEKH */
    HZ_JOINING_TYPE_D, /* NKO FA */
    HZ_JOINING_TYPE_D, /* NKO LA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* DOTLESS TEH MARBUTA */
    HZ_JOINING_TYPE_D, /* NKO TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SWASH << 6), /* SWASH KAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* NKO WA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN SADHE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FINAL << 6), /* FINAL SEMKATH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ANG */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO TSA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* DOTLESS DALATH RISH */
    HZ_JOINING_TYPE_D, /* MANDAIC AD */
    HZ_JOINING_TYPE_U, /* ARABIC FOOTNOTE MARKER */
    HZ_JOINING_TYPE_D, /* MONGOLIAN HAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEMKATH << 6), /* SEMKATH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN WAW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_HE << 6), /* HE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE GA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI NGA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SANAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NUN << 6), /* NUN */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI UBADAMA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DOT BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AK */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* DOTLESS NOON */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN DALETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TETH << 6), /* TETH GARSHUNI */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* FEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_REVERSED << 6), /* REVERSED PE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO YA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BURUSHASKI << 6), /* BURUSHASKI YEH BARREE WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 4 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* FEH WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI ZHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YUDH << 6), /* YUDH HE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT BELOW */
    HZ_JOINING_TYPE_R, /* MANDAIC ASH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI DDHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN FA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI YODH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI KA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ZAYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALAPH << 6), /* ALAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* HIGH HAMZA DOTLESS YEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN */
    HZ_JOINING_TYPE_D, /* MANDAIC AN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH BAR */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH TAH ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ZA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN U */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SHIN << 6), /* SHIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_PE << 6), /* PE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FE << 6), /* SOGDIAN FE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI TEN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN CHI */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN A */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI KAPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED V BELOW */
    HZ_JOINING_TYPE_D, /* NKO PA */
    HZ_JOINING_TYPE_R, /* MANDAIC AZ */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI HE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_STRAIGHT << 6), /* STRAIGHT WAW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF */
    HZ_JOINING_TYPE_U, /* HIGH HAMZA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO MA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI NNA */
    HZ_JOINING_TYPE_D, /* NKO DA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN AYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MIM << 6), /* MIM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAPH << 6), /* QAPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TWENTY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* MANDAIC KAD */
    HZ_JOINING_TYPE_D, /* MONGOLIAN PA */
    HZ_JOINING_TYPE_D, /* NKO BA */
    HZ_JOINING_TYPE_C, /* NKO LAJANYALAN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH ATTACHED RING WITHIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DOT WITHIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TTHA */
    HZ_JOINING_TYPE_C, /* ZERO WIDTH JOINER */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI DHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO CHA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN VOWEL SEPARATOR */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI PHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU FA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NYA << 6), /* NYA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE JA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE SHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO I */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN HUNDRED */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE UE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YUDH << 6), /* YUDH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* PERSIAN DHALATH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI VISARGA ONE */
    HZ_JOINING_TYPE_D, /* NKO YA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ROHINGYA << 6), /* ROHINGYA YEH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL */
    HZ_JOINING_TYPE_D, /* NKO JONA JA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TEN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN NA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI ZA */
    HZ_JOINING_TYPE_D, /* NKO GBA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO GAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* QAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 2 DOTS BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE GAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI ONE */
    HZ_JOINING_TYPE_D, /* NKO NYA WOLOSO */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KNOTTED << 6), /* KNOTTED HEH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* NKO KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI SSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN FIVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI SHIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ANG */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* HIGH HAMZA WAW WITH DAMMA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH MADDA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ZAIN << 6), /* ZAIN */
    HZ_JOINING_TYPE_D, /* MANDAIC AP */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_SYRIAC << 6), /* WAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI JHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI CA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* HIGH HAMZA ALEF */
    HZ_JOINING_TYPE_D, /* NKO U */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SHA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI TWO */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN MEM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* QAF WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH LOOP */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH BAR */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI DALETH */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI TWENTY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* PERSIAN GHAMAL */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH TAH ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC IT */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO WA */
    HZ_JOINING_TYPE_U, /* MANICHAEAN SHIN */
    HZ_JOINING_TYPE_D, /* MANDAIC AT */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH ALEF ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KHAPH << 6), /* SOGDIAN KHAPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* DOTLESS NOON WITH TAH ABOVE */
    HZ_JOINING_TYPE_U, /* MANDAIC DUSHENNA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI LHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* DALATH */
    HZ_JOINING_TYPE_U, /* MANICHAEAN JAYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO U */
    HZ_JOINING_TYPE_U, /* MANICHAEAN HE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI LAMEDH */
    HZ_JOINING_TYPE_U, /* MANICHAEAN UD */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH AND 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN O */
    HZ_JOINING_TYPE_L | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN HETH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO QA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI CA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BURUSHASKI << 6), /* BURUSHASKI YEH BARREE WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH V ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI NUN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* NKO NA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BETH << 6), /* PERSIAN BHETH */
    HZ_JOINING_TYPE_U, /* LOW ALEF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TTA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WAVY HAMZA ABOVE */
    HZ_JOINING_TYPE_U, /* PSALTER PAHLAVI HUNDRED */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI FOUR */
    HZ_JOINING_TYPE_D, /* MANDAIC AS */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE CHA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI GIMEL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ALI GALI ZHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO OE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO JIA */
    HZ_JOINING_TYPE_U, /* ARABIC NUMBER MARK ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 2 DOTS AND TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH V BELOW */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI HETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH DIGIT FOUR BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI I */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI BETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH BARREE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN AYIN */
    HZ_JOINING_TYPE_D, /* MANDAIC AG */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN WA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN DA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI AH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI HALF YA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI TTA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN SAMEKH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE U */
    HZ_JOINING_TYPE_D, /* NKO CHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 4 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN GIMEL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI A */
    HZ_JOINING_TYPE_D, /* NKO A */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH DOT ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI PE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI DDA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SA */
    HZ_JOINING_TYPE_R, /* MANDAIC IN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH DOT BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZHI */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE HAA */
    HZ_JOINING_TYPE_D, /* NKO RA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI ZAYIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI HALF U */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT AND INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_C, /* MONGOLIAN NIRUGU */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN RA */
    HZ_JOINING_TYPE_D, /* MANDAIC ASZ */
    HZ_JOINING_TYPE_D, /* NKO I */
    HZ_JOINING_TYPE_D, /* MANDAIC AB */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU I */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE TSA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO O */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO HAA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN JA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO JA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* FIRST STRONG ISOLATE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ZAYIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI TA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH DOUBLE BAR */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 2 DOTS AND TAH ABOVE */
    HZ_JOINING_TYPE_U, /* MANICHAEAN JAYIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO LONG VOWEL SIGN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ALEPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH STROKE BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DIGIT FOUR BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO UE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DIGIT FOUR ABOVE */
    HZ_JOINING_TYPE_D, /* NKO RRA */
    HZ_JOINING_TYPE_U, /* MANICHAEAN SHIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN DHAMEDH */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI SADHE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO DZA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI DAMARU */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MANDAIC USHENNA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED V BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI NGA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI THREE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ANG */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* GAMAL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZRA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WAVY HAMZA BELOW */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI INVERTED UBADAMA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN BETH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN LAMEDH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH BARREE WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO TA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE TA */
    HZ_JOINING_TYPE_U, /* MANDAIC AIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN EE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN QA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI TAW */
    HZ_JOINING_TYPE_D, /* MANDAIC AM */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ZHA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI ALEPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI SSA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO DA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI DA */
};

#endif /* HZ_UCD_7_0_0_H */
