#ifndef HZ_UCD_11_0_0_H
#define HZ_UCD_11_0_0_H

#include <stdint.h>

#define HZ_UCD_VERSION HZ_MAKE_VERSION(11,0,0)

uint16_t hz_ucd_arabic_joining_k2[675] = {
      23,   2,   1,   5,   0,   1,
       1,  12,   1,   0,   0,   1,
       2,   0,   0,   2,   0,   2,
       2,   2,   0,   1,   4,   1,
       5,   0,   3,   2,   0,  14,
       0,   2,   1,   0,   1,   0,
      10,   0,   2,   0,   1,   3,
       4,   9,   1,   1,   6,   6,
      10,   0,   5,   1,   2,   2,
       6,  17,   0,   0,   6,  17,
       0,   0,  19,   0,   0,   0,
       1,  81,   1,  68,   0,   1,
     124,   2,   0,   1, 120,   1,
      25,  53,   0,   3,   3,   2,
       0,   0,   4,   0,   4,   0,
       1,   0,   0,   0,  17,   3,
      11,   6,   0,  17,   3,  16,
       1,   3,   1,   2,   0,   3,
       1,   0,   5,   0,   0,   4,
       3,   0,   0,   1,   3,   1,
       7,  14,   3,   0,   4,  10,
       4,   0,   0,   0,   1,   6,
       2,   3,   3,   1,  16,   1,
       2,  12,   1,   0,   4,   0,
       3,   0,   0,   1,   2,   0,
       2,   1,   1,   6,   3,   1,
       4,   0,   1,   1,   1,   5,
       3,   2,   0,   2,   3,   2,
       1,   1,   0,   1,   0,   5,
       0,   0,   9,   0,   0,   0,
       6,   3,   1,   0,   0,  13,
       3,   0,   6,   1,   1,   3,
       3,   2,   1,   0,   3,   2,
       1,   2,   0,   0,   1,   8,
      14,   2,   8,   0,   1,   1,
       0,   1,   0,   3,   1,   0,
       1,   0,   5,   0,   6,   5,
       4,   0,   0,  11,   3,   4,
       0,   0,   0,   3,  10,   2,
       6,   0,   0,   1,   1,   9,
       1,   2,   1,   1,   0,   0,
       0,   0,   1,   1,   1,   1,
       1,   3,   2,   1,   0,   7,
       2,   0,   0,   0,   3,   2,
       3,   1,   4,   1,   0,   4,
       0,   3,   0,   0,   1,   5,
       1,  15,   0,   0,   2,   3,
       0,   1,   2,   4,   1,   6,
       6,   0,   1,   0,   2,   5,
       0,   7,   0,   5,   2,   5,
       1,   0,   0,   0,   1,   6,
       0,   0,   0,  11,   3,   0,
       1,   6,   1,   0,  15,   2,
       0,   0,   3,   7,   0,   0,
       0,   0,   0,   0,   9,  15,
       1,   3,   0,   9,   0,  11,
       3,  10,   0,   0,   4,   2,
       5,  11,   0,   0,  13,   0,
       1,   1,   4,  11,  19,   0,
       0,   2,  11,  14,   0,   3,
       5,   0,   0,   3,   0,  36,
       2,   2,  21,   0,   3,   3,
       0,   0,  17,   2,   0,   6,
       8,  12,   1,  25,  18,   3,
       6,   0,   0,   1,   0,   3,
       1,   0,   0,   0,   7,   0,
       0,   0,   0,   1,   0,   0,
       0,  20,  81,   2,   3,   1,
       1,   0,   0,   1,   3,   0,
      18,   0,  53,  15,   0,   0,
       0,   0,   0,   9,   3,   3,
       0,   0,   0,   0,  41,   1,
       0,  24,   1,  53,   1,   1,
       0,   0, 192,   0,   0,   2,
       0,  54,   0,  25,   1,  75,
       0,  73,   0,   0,   0,   1,
      10,  33,   0,   5,   1,  28,
      45,   0,   7,   0,   1,  61,
      26,  24,  88,   0,   0,   0,
       0,   2,   0,  94,   1,  10,
       0,   0,   0,   6,   6,   3,
       1,   0,   9,  17,   0,   8,
       1,  19,   1,   1,  21,   1,
      42,   1,   0,   0,  11,   0,
       0,  11,   7,  35,   0,  38,
       0,   0,  23,   2,   1,   1,
      17,   7,   3,   1,   2,   0,
       8,   3,   1,  23,   5,  18,
       5,   1,   3,   1,   7,   3,
       9,   3,   1,   1,   0,  13,
       6,   1,   6,   0,   2,   2,
       3,   0,   1,   0,   2,   2,
       5,   1,   0,   0,   8,   0,
       0,   0,   8,   4,   0,   0,
       1,   1,   1,   1,   0,   5,
       0,   4,   3,   0,   0,  10,
       0,   6,   6,   2,   2,   0,
       1,   0,   1,   0,   0,   1,
       8,   0,   0,   0,   1,   4,
       5,   0,   5,   0,   1,   1,
       2,   6,   2,   1,   0,   0,
       3,   0,   2,   0,   0,   5,
       0,   1,   0,   4,   2,   1,
       0,   2,   1,   1,   1,   0,
       1,   2,   2,   1,   0,   7,
       1,   4,   1,   4,   0,   2,
       0,   5,   3,   2,   2,   0,
       1,   0,   0,   9,   0,   1,
       2,   1,   4,   0,   0,  13,
       8,   0,   3,   0,   1,   0,
       0,   0,  14,   2,   1,   8,
       2,   6,   0,   1,   0,   2,
       1,  87,   9,
};

uint32_t hz_ucd_arabic_joining_ucs[675] = {
        1658,    6212,   68331,    1746,    1590,    1837,
      125242,    2113,    2014,    1731,    2208,    1691,
        1676,    1775,    6177,    1707,    1874,    1704,
        6204,    2008,    1665,    2230,    1607,   68868,
        2127,    1670,    2116,    1596,    1683,    1684,
        2147,    1701,    1576,    6200,    2016,    2003,
        1718,    1911,   68317,    1662,    2214,    1870,
        1917,    1717,    1724,    1674,    1703,    1891,
        6256,    6234,   69425,  125193,    2121,    2218,
        1822,    6253,    1791,    1885,   68296,   68877,
        1720,    6304,    1901,    2117,   68334,   68864,
        2005,    1573,    1667,    6242,   68304,    1735,
        6247,    2126,  125244,    1883,    6236,    1685,
        1651,   68291,    2015,   68521,   68289,    1739,
        1650,   68292,    6243,    1604,    2223,    2018,
        6223,    1671,    6150,   68488,    1659,    1882,
      125209,   68889,    2122,    2151,    1723,    6184,
        1666,    6229,   68306,    6286,    6308,   68300,
        2131,    1817,   68298,    1786,    2216,   68320,
        1903,    1824,    1544,    1915,    1813,    1588,
       68318,    6224,   68878,    1829,    1839,   68886,
       68314,    6298,    1897,    6209,    1807,    2152,
       68873,    6227,    1912,    6190,    1909,    1587,
        1574,   68483,   68309,    6284,    1749,    6293,
        1572,    1828,  125199,   68487,    2019,    1774,
        1668,    1657,    1570,    1647,    6180,   68875,
        6182,    2132,    2150,    1821,    2013,    1696,
        2227,    6285,    1679,    6300,    2228,    1894,
       68295,    6302,   68898,    1906,    2154,    1541,
        6186,    1714,    1916,    1540,    1579,    6292,
        1918,    6287,    2123,    1654,    2133,    1699,
        1681,    1689,  125241,    2002,    6257,   69432,
        1656,  125228,    6277,   68311,    1819,   69430,
        2009,    1599,    1820,    2000,    6259,   68288,
       68481,    1728,    6193,    6231,    6195,    2219,
       68883,    2220,   69460,    1539,    1732,    1902,
       68867,    1584,    2215,    1999,    1700,    6245,
        6219,    2136,    6222,    6198,    1586,    6216,
        1733,  125239,   69435,    1682,    1827,  125245,
        1825,    2001,   68492,    1875,   69431,    2025,
        1581,    1835,    2010,   68332,  125185,   68524,
        1697,    6178,    1694,    6196,    1757,   68888,
        8205,    2213,    6214,    1738,    1878,    2130,
        1895,   68892,   68523,   68482,    1812,    1899,
        6263,    1873,    2124,  125187,    1905,   69837,
      125191,    2026,   69442,    2148,  125224,    1722,
        1892,  125211,    1655,   68316,    6217,    1743,
        1996,    2020,    1710,    2023,  125210,    1589,
        2144,    1538,    1744,  125229,    6235,    1913,
       68486,    6158,    6201,    1695,    1606,    1900,
       68866,    6261,    6221,    1677,    1595,    2115,
        2112,    1688,    2233,   68525,    6260,    6176,
        1678,    1692,    2232,  125230,    1690,   68527,
       68301,    2006,    2118,    1583,    1601,   68895,
        1823,    1578,    2135,    2042,    1834,  125227,
        2225,    1664,    1712,    6305,    2224,   68305,
        6282,    2145,    2217,    1591,    1830,    6281,
        1833,   68526,    1826,    6233,    2021,    6210,
        1609,    1884,    1597,    1788,    1577,    1603,
        1877,    1740,   68897,   68884,    2012,    6301,
       69434,    1886,    1814,    1610,    2237,  125204,
        6215,    2114,  125192,   69821,   68319,    1536,
      125198,    1547,    6189,   68335,    1888,    2221,
        6283,    1995,  125208,  125231,    2274,    1730,
       68497,  125219,   69445,    2119,    1872,    6255,
        1702,    1673,    1715,    1719,   68324,    6258,
        1727,    1705,    6297,    6206,    6187,   68484,
        6192,   69433,    6276,    2236,    6202,   69457,
        1605,    6311,    6244,    2222,    1818,    1747,
        6264,    6280,    2153,    1602,    1593,    2210,
        2125,    1745,    1569,  125235,    6185,   68881,
        6307,    2235,    1880,    1808,    6274,    1838,
        1680,    1672,    1898,    1907,  125217,    1908,
        1711,    6237,    1811,    6278,   68893,    1716,
        1737,    6203,    2129,   68493,    1816,    1709,
       68882,    6272,    6179,    6218,  125215,    1598,
        1896,    1881,    1742,   68307,   68874,    1575,
        6220,  125225,    6246,    6250,  125222,   69427,
        1726,   68299,    1810,  125188,    2134,    1890,
       68871,    1741,    6226,   68872,    1669,   68315,
       69436,    1836,   68891,   68313,    1649,    1660,
        1734,    1815,    6273,    6299,    1580,   69443,
        2211,    1736,    6306,    1998,    6188,    1914,
      125249,    6296,   68333,    1721,    1889,    6314,
       68303,  125189,   68490,    6290,   68290,    6181,
       68293,    6275,    6309,    6191,    1831,   68876,
        2022,    1698,   69459,    6183,   69438,    1687,
        6295,    2209,    1919,    1646,   68879,    6294,
      125238,   69439,   68496,  125184,    2212,   68312,
        8297,   68322,    6205,    1585,  125243,    6254,
      125197,    2146,  125218,   68323,  125221,    2149,
       68899,  125216,  125240,  125220,  125212,    6288,
        8296,    1608,    1686,   68870,   69429,  125214,
       68865,  125223,   68522,    6194,   69444,    1568,
      125251,    6211,  125233,    1594,   68480,    6262,
      125205,    1571,    6228,    1879,    6291,   68890,
        6312,  125202,   68494,    1582,    6230,    6240,
      125226,   68885,    1592,  125237,    1787,  125190,
       68302,   68869,    2226,    6207,    2231,    1869,
        1887,    1653,    1893,    6238,  125195,  125234,
      125201,    1904,   69441,    6151,   68308,    6310,
        6199,    6248,   68887,    2017,    2004,    6241,
        6252,    1729,    1537,    1663,  125206,   68489,
        1997,   69458,   69424,   68321,   68880,    2128,
      125194,   69428,  125246,    1600,    6251,  125247,
        6197,    1713,  125232,    1994,  125200,    1693,
       68310,    1661,    6225,   68495,    1725,    6249,
      125213,    6208,    2011,   69437,  125207,    1708,
       68297,    6279,   69426,  125186,    6289,  125250,
        2234,    6239,    6154,    6232,    2024,  125236,
      125196,    1871,    1832,    6303,    1706,   68294,
        6213,  125248,  125203,    2007,    1910,    1675,
        1652,    2120,    1876,
};

uint32_t hz_ucd_arabic_joining_data[675] = {
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ONE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH BARREE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BETH << 6), /* PERSIAN BHETH */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL GA */
    HZ_JOINING_TYPE_D, /* MANDAIC AB */
    HZ_JOINING_TYPE_D, /* NKO KA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* TEH MARBUTA GOAL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH V BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TSA */
    HZ_JOINING_TYPE_D, /* NKO DA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH MEEM ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA TTA */
    HZ_JOINING_TYPE_D, /* MANDAIC IN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MANDAIC AH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM TTA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN WA */
    HZ_JOINING_TYPE_D, /* NKO NA WOLOSO */
    HZ_JOINING_TYPE_D, /* NKO BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH DIGIT FOUR BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN SADHE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH DOUBLE BAR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KHAPH << 6), /* SOGDIAN KHAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DIGIT FOUR ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE RAA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO JIA */
    HZ_JOINING_TYPE_D, /* SOGDIAN BETH */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL E */
    HZ_JOINING_TYPE_R, /* MANDAIC AKSA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH LOOP */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YUDH << 6), /* YUDH HE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE HAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KNOTTED << 6), /* KNOTTED HEH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* MANICHAEAN UD */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA RRA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC USHENNA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TWENTY */
    HZ_JOINING_TYPE_L, /* HANIFI ROHINGYA A */
    HZ_JOINING_TYPE_D, /* NKO TA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH HAMZA BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ANG */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DAMMA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE SHA */
    HZ_JOINING_TYPE_D, /* MANDAIC AS */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL TU */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH BAR */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO DZA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH V BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WAVY HAMZA BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN GIMEL */
    HZ_JOINING_TYPE_D, /* NKO LA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI ONE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN BETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WAVY HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN GIMEL WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE KA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* NKO NYA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO MA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 4 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* MONGOLIAN TODO SOFT HYPHEN */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI YODH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED V BELOW */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL NYA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HANIFI << 6), /* HANIFI ROHINGYA KINNA YA */
    HZ_JOINING_TYPE_D, /* MANDAIC AK */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM RA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* DOTLESS NOON WITH TAH ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN NA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO YA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI DDA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI ZHA */
    HZ_JOINING_TYPE_U, /* MANICHAEAN JAYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AR */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ZAIN << 6), /* ZAIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ZAYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DOT BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH AND 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAMADH << 6), /* LAMADH */
    HZ_JOINING_TYPE_U, /* ARABIC RAY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BURUSHASKI << 6), /* BURUSHASKI YEH BARREE WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* DALATH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO TA */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA ZA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_E << 6), /* E */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* PERSIAN DHALATH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA WA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN AYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI GHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZHI */
    HZ_JOINING_TYPE_T, /* SYRIAC ABBREVIATION MARK */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM LLA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HANIFI << 6), /* HANIFI ROHINGYA PA WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO JA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI DALETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN THAMEDH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TTA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* DOTLESS TEH MARBUTA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI ZHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FINAL << 6), /* FINAL SEMKATH */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL WAW */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI HETH */
    HZ_JOINING_TYPE_D, /* NKO NA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH MADDA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN U */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA DDA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN UE */
    HZ_JOINING_TYPE_R, /* MANDAIC ASH */
    HZ_JOINING_TYPE_U | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM BHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YUDH << 6), /* YUDH */
    HZ_JOINING_TYPE_D, /* NKO FA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TTHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI CA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH DOT BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN WAW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI TTA */
    HZ_JOINING_TYPE_R, /* HANIFI ROHINGYA SAKIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM SSA */
    HZ_JOINING_TYPE_U, /* ARABIC NUMBER MARK ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DIGIT FOUR BELOW */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SAMVAT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI SSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI NNA */
    HZ_JOINING_TYPE_D, /* MANDAIC AL */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* HIGH HAMZA WAW */
    HZ_JOINING_TYPE_D, /* MANDAIC AT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* FEH WITH DOT BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL QAAF */
    HZ_JOINING_TYPE_D, /* NKO N */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE CHA */
    HZ_JOINING_TYPE_D, /* SOGDIAN KAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* HIGH HAMZA DOTLESS YEH */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL FA */
    HZ_JOINING_TYPE_T, /* MONGOLIAN ALI GALI BALUDA */
    HZ_JOINING_TYPE_L | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN NUN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TETH << 6), /* TETH */
    HZ_JOINING_TYPE_D, /* SOGDIAN HETH */
    HZ_JOINING_TYPE_D, /* NKO RA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TETH << 6), /* TETH GARSHUNI */
    HZ_JOINING_TYPE_D, /* NKO O */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ALEPH */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI BETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* DOTLESS TEH MARBUTA WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN DA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DOT WITHIN */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA LA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ROHINGYA << 6), /* ROHINGYA YEH */
    HZ_JOINING_TYPE_R, /* SOGDIAN ONE HUNDRED */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SAFHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH ATTACHED RING WITHIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH BELOW */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA TA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* NKO OO */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE HA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO BA */
    HZ_JOINING_TYPE_U, /* MANDAIC AIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO GA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN YA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO OE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH BAR */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL CHI */
    HZ_JOINING_TYPE_D, /* SOGDIAN NUN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEMKATH << 6), /* SEMKATH */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL NHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MIM << 6), /* MIM */
    HZ_JOINING_TYPE_D, /* NKO DAGBASINNA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI NUN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* SOGDIAN YODH */
    HZ_JOINING_TYPE_D, /* NKO JONA CHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SHIN << 6), /* SHIN */
    HZ_JOINING_TYPE_D, /* NKO RRA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN FIVE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL DAALI */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI FOUR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN CHA */
    HZ_JOINING_TYPE_U, /* ARABIC END OF AYAH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA YA */
    HZ_JOINING_TYPE_C, /* ZERO WIDTH JOINER */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* QAF WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO O */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AQ */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HANIFI << 6), /* HANIFI ROHINGYA PA WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI THREE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI GIMEL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* GAMAL GARSHUNI */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ZHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AM */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL MIIM */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 2 DOTS AND TAH ABOVE */
    HZ_JOINING_TYPE_U, /* KAITHI NUMBER SIGN ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL BHE */
    HZ_JOINING_TYPE_D, /* NKO JONA RA */
    HZ_JOINING_TYPE_D, /* SOGDIAN TAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM NNA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL PE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* DOTLESS NOON */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL NHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* HIGH HAMZA WAW WITH DAMMA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN PE WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO UE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* NKO I */
    HZ_JOINING_TYPE_D, /* NKO HA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* NKO NYA WOLOSO */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL TU */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM NGA */
    HZ_JOINING_TYPE_U, /* ARABIC FOOTNOTE MARKER */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL I */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO NIA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI ZAYIN */
    HZ_JOINING_TYPE_U, /* MONGOLIAN VOWEL SEPARATOR */
    HZ_JOINING_TYPE_D, /* MONGOLIAN FA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HANIFI << 6), /* HANIFI ROHINGYA PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU RA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO QA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AD */
    HZ_JOINING_TYPE_R, /* MANDAIC HALQA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH NOON ABOVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI TEN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN A */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH TEH ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL O */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_U, /* PSALTER PAHLAVI HUNDRED */
    HZ_JOINING_TYPE_L | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN HETH */
    HZ_JOINING_TYPE_D, /* NKO JA */
    HZ_JOINING_TYPE_R, /* MANDAIC AZ */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* FEH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA VOWEL U */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAPH << 6), /* KAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* MANDAIC KAD */
    HZ_JOINING_TYPE_C, /* NKO LAJANYALAN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* RISH */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL E */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_STRAIGHT << 6), /* STRAIGHT WAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 4 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI DHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH STROKE BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI NGA */
    HZ_JOINING_TYPE_U | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM JA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_PE << 6), /* PE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI KA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAPH << 6), /* QAPH */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI TWENTY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NUN << 6), /* NUN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO HAA */
    HZ_JOINING_TYPE_D, /* NKO WA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN CHI */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* TEH MARBUTA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED V BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA VOWEL O */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA MA */
    HZ_JOINING_TYPE_D, /* NKO GBA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI JHA */
    HZ_JOINING_TYPE_D, /* SOGDIAN MEM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* DOTLESS DALATH RISH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AFRICAN << 6), /* AFRICAN NOON */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL JIIM */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO U */
    HZ_JOINING_TYPE_D, /* MANDAIC AG */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL RA */
    HZ_JOINING_TYPE_U, /* KAITHI NUMBER SIGN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH WITH DOT ABOVE */
    HZ_JOINING_TYPE_U, /* ARABIC NUMBER SIGN */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL YHE */
    HZ_JOINING_TYPE_U, /* AFGHANI SIGN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN GA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN HUNDRED */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* LOW ALEF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI CA */
    HZ_JOINING_TYPE_D, /* NKO EE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL GA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL DHA */
    HZ_JOINING_TYPE_U, /* ARABIC DISPUTED END OF AYAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH GOAL WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI TAW */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL DAALI */
    HZ_JOINING_TYPE_U, /* SOGDIAN INDEPENDENT SHIN */
    HZ_JOINING_TYPE_R, /* MANDAIC IT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH HORIZONTAL 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ZA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TAW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ZHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ALI GALI ZHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN HAA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN PA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI HE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SA */
    HZ_JOINING_TYPE_D, /* SOGDIAN LAMEDH */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI INVERTED UBADAMA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AFRICAN << 6), /* AFRICAN QAF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN KA */
    HZ_JOINING_TYPE_D, /* SOGDIAN ONE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI HALF YA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE GA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HETH << 6), /* HETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH BARREE WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU CHA WITH 2 DOTS */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI I */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM LLLA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* QAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* HAMZA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL KAF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ANG */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI CYA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AFRICAN << 6), /* AFRICAN FEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALAPH << 6), /* ALAPH */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI DAMARU */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* PERSIAN GHAMAL */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH BAR */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL SHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* GAMAL */
    HZ_JOINING_TYPE_T, /* MONGOLIAN ALI GALI THREE BALUDA */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA VOWEL A */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN KHA */
    HZ_JOINING_TYPE_D, /* MANDAIC ASZ */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI SAMEKH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_SYRIAC << 6), /* WAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA GA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI ANUSVARA ONE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN O */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ANG */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL ZAL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH VERTICAL 2 DOTS BELOW AND TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN LAMEDH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA DA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO PA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL BHE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE JA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL BA */
    HZ_JOINING_TYPE_R, /* SOGDIAN HE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KNOTTED << 6), /* KNOTTED HEH */
    HZ_JOINING_TYPE_U, /* MANICHAEAN JAYIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BETH << 6), /* BETH */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL BA */
    HZ_JOINING_TYPE_U, /* MANDAIC DUSHENNA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA HA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH TAIL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO CHA */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA KHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN PE */
    HZ_JOINING_TYPE_D, /* SOGDIAN SAMEKH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TAW << 6), /* TAW */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA NYA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN AYIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WASLA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH ATTACHED RING BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH V ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_HE << 6), /* HE */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI VISARGA ONE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI NGA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* SOGDIAN FETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH ALEF ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI SSA */
    HZ_JOINING_TYPE_D, /* NKO U */
    HZ_JOINING_TYPE_D, /* MONGOLIAN QA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BURUSHASKI << 6), /* BURUSHASKI YEH BARREE WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL ZAL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ALI GALI TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TEN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI LHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN YODH */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL SINNYIIYHE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI LAMEDH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI PA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN BETH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN OE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN DALETH */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI UBADAMA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI ZA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN LA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_REVERSED << 6), /* REVERSED PE */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA RA */
    HZ_JOINING_TYPE_D, /* NKO YA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* SOGDIAN TWENTY */
    HZ_JOINING_TYPE_D, /* MONGOLIAN EE */
    HZ_JOINING_TYPE_D, /* SOGDIAN PE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI AH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA SA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI ZA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL JIIM */
    HZ_JOINING_TYPE_D, /* SOGDIAN SADHE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI SHIN */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL ALIF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH DOT BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN SAMEKH */
    HZ_JOINING_TYPE_U, /* POP DIRECTIONAL ISOLATE */
    HZ_JOINING_TYPE_U, /* MANICHAEAN SHIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL NYA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE TSA */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL DHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM NYA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL ALIF */
    HZ_JOINING_TYPE_U, /* MANICHAEAN SHIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL MIIM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MALAYALAM << 6), /* MALAYALAM NNNA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HANIFI << 6), /* HANIFI ROHINGYA DOTLESS KINNA YA WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL KPO */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL HA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL LAAM */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL VA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TA */
    HZ_JOINING_TYPE_U, /* FIRST STRONG ISOLATE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT BELOW AND DOT WITHIN */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA CA */
    HZ_JOINING_TYPE_D, /* SOGDIAN ZAYIN */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL GBE */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA BA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL SINNYIIYHE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI TWO */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TA */
    HZ_JOINING_TYPE_D, /* SOGDIAN LESH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH SEPARATE RING BELOW */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL SHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO LONG VOWEL SIGN */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL WAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI ALEPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU FA */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL CHI */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO TSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI PHA */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA NGA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI BHA */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL YA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI PE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO WA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE UE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL RA */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA NA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL U */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL PE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TETH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA JA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT AND INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZRA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS BELOW AND MEEM ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ZHAIN << 6), /* SOGDIAN ZHAIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* HIGH HAMZA ALEF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE I */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL I */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL NUN */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL KAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 2 DOTS AND TAH ABOVE */
    HZ_JOINING_TYPE_D, /* SOGDIAN SHIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN DHAMEDH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI HALF U */
    HZ_JOINING_TYPE_D, /* MONGOLIAN RA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE TA */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA KINNA WA */
    HZ_JOINING_TYPE_D, /* NKO MA */
    HZ_JOINING_TYPE_D, /* NKO PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE U */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE GAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH GOAL */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SANAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL HA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI KAPH */
    HZ_JOINING_TYPE_D, /* NKO E */
    HZ_JOINING_TYPE_D, /* SOGDIAN TEN */
    HZ_JOINING_TYPE_D, /* SOGDIAN ALEPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN RESH */
    HZ_JOINING_TYPE_D, /* HANIFI ROHINGYA SHA */
    HZ_JOINING_TYPE_D, /* MANDAIC AP */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL FA */
    HZ_JOINING_TYPE_D, /* SOGDIAN WAW */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL VA */
    HZ_JOINING_TYPE_C, /* TATWEEL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE FA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL KHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN JA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL YHE */
    HZ_JOINING_TYPE_D, /* NKO A */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL NUN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN MEM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO DA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI SADHE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NYA << 6), /* NYA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE DA */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL KHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN LHA */
    HZ_JOINING_TYPE_D, /* NKO SA */
    HZ_JOINING_TYPE_D, /* SOGDIAN AYIN */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL QAAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ZAYIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI A */
    HZ_JOINING_TYPE_D, /* SOGDIAN GIMEL */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL LAAM */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI DA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL KPO */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH NOON ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE IY */
    HZ_JOINING_TYPE_C, /* MONGOLIAN NIRUGU */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO GAA */
    HZ_JOINING_TYPE_D, /* NKO JONA JA */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL YA */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL O */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FE << 6), /* SOGDIAN FE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_SADHE << 6), /* SADHE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI DDHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SWASH << 6), /* SWASH KAF */
    HZ_JOINING_TYPE_U, /* MANICHAEAN HE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO I */
    HZ_JOINING_TYPE_D, /* ADLAM SMALL GBE */
    HZ_JOINING_TYPE_D, /* ADLAM CAPITAL U */
    HZ_JOINING_TYPE_D, /* NKO CHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT BELOW AND TAH ABOVE */
    HZ_JOINING_TYPE_U, /* HIGH HAMZA */
    HZ_JOINING_TYPE_D, /* MANDAIC ATT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 2 DOTS BELOW AND DOT ABOVE */
};

#endif /* HZ_UCD_11_0_0_H */
