#ifndef HZ_UCD_8_0_0_H
#define HZ_UCD_8_0_0_H

#include <stdint.h>

#define HZ_UCD_VERSION HZ_MAKE_VERSION(8,0,0)

uint16_t hz_ucd_arabic_joining_k2[524] = {
       0,   1,  28,  30,   4,   0,
       6,  24,   1,   2,   0,   5,
       0,   0,   9,   0,  30,   0,
      10,   0,  30,   0,   0,   3,
       4,  12,   4,  17,   1,   1,
       0,   9,   2,   0,  16,   2,
       0,  19,   1,   8,  17,   0,
      10,   1,   0,   0,   0,   8,
       9,   0,   1,   3,  15,   0,
       1,   2,   4,  14,   0,   4,
       1,   0,   0,   3,   0,   5,
       4,   4,   1,   2,   2,   1,
       7,   1,   1,   3,   3,   0,
       0,   0,   8,   0,   1,   0,
       0,  14,   1,   2,   9,   1,
       0,   0,   4,   2,   1,   4,
       1,   0,   9,   2,   4,   0,
       0,   1,   3,   0,   0,   4,
       2,   0,   0,   9,   2,   0,
       1,   7,   3,   0,   2,   0,
       1,   2,   4,   1,   0,   0,
       2,   0,   3,   4,   0,   1,
       3,   0,   4,   3,   1,   0,
       1,   8,   0,   0,   6,   0,
       0,   1,   6,   0,   1,   0,
       4,   0,   1,   9,   6,   0,
       0,   6,   0,   0,   0,   2,
       5,   1,   0,   9,   8,   0,
       2,   0,   3,   2,   9,   0,
       0,   0,   1,   4,   0,   1,
       0,   5,   3,   9,   0,   0,
       0,   0,   2,   0,   1,   0,
       1,   0,   3,   2,   6,   0,
       1,   7,   2,   0,   0,   1,
       0,   1,   5,   4,   0,   2,
       0,   0,   0,   2,   1,   2,
       2,   0,   1,   2,   4,  12,
      13,   5,   1,  14,   0,   1,
       4,   2,   5,   0,   0,   0,
       0,   0,   0,   1,   0,   2,
       2,   6,   6,   0,   0,   2,
       0,   0,   5,   0,  19,   1,
       1,   0,   2,   3,   3,  19,
       5,   0,   5,   6,   0,   3,
       1,   0,   1,   0,   0,   1,
       3,  20,   6,   5,   3,  10,
       1,   2,   3,   4,  44,   0,
       0,   8,   0,   0,   0,   4,
       2,   0,   0,  13,   0,   3,
       5,   6,   0,   0,   1,   4,
       2,   2,  36,   2,   0,   2,
       0,   0,   5,  10,   9,  11,
       0,   0,  21,  42,   0,  64,
      18,   0,   2,  12,   0, 275,
     493,1017,   6,   2,   0,   0,
       0,   0,  15,   1,  55,   0,
       2,   1,   0,   2,  40,  29,
       3,   0,   4,   1,   1,  10,
       0,   6,   1,  11,   0,   1,
       1,   3,   1,   1,   0,   0,
       0,   0,   0,   5,   3,  18,
       2,   0,   1,   1,   0,   3,
       0,   1,   1,   1,   0,  22,
       5,   0,   1,   0,   1,   0,
       3,   0,   2,  20,   0,   6,
       3,   6,   0,  10,   1,   1,
       2,   3,   0,   2,   0,   3,
       2,   0,   3,   0,   0,   4,
       2,   0,   1,   0,   0,   0,
      12,   0,   0,   0,   2,   2,
       3,   1,   0,   6,   1,   1,
      13,   3,   0,   0,   0,   7,
       0,   7,   1,   3,   3,   0,
       0,   4,   1,   0,   1,   1,
       0,   0,   1,   3,   8,   1,
       1,   0,   2,   0,   1,   9,
       0,   1,   0,   5,   3,   2,
       4,   5,   0,   1,   0,   0,
       2,   0,   0,   0,   1,   0,
       1,   0,   0,   1,   0,   3,
       0,   0,   2,   1,   1,   1,
       0,   0,   0,   0,   0,   0,
       6,   0,   0,   2,   1,   0,
       6,   2,   1,   3,   0,   3,
       4,   0,  18,   0,  22,   0,
       6,   6,   3,  69,   1,   2,
       5,  37,   0,   0,   3,  50,
      29,   0,
};

uint32_t hz_ucd_arabic_joining_ucs[524] = {
        2216,    6314,    1724,    6308,    1651,    6246,
        1537,    1571,    6194,    1787,    1917,    2015,
       68309,    1892,    1818,    1575,    1713,    1999,
        2017,    6244,    2003,    1894,    1699,    1601,
        1582,    1588,    1592,    2023,    6281,    2221,
        1883,    1609,    1716,    1839,    6205,    2222,
        1650,    2120,    1811,    1598,    6154,    1667,
        1757,    1734,   68294,    1997,    1833,    1914,
        1578,   68521,    6217,    1909,    6237,    1657,
        1915,    2019,    1908,    1869,    1875,    2118,
        2219,    1702,   68317,    1834,    2008,    1706,
        1719,    6220,    6279,    1736,    2011,    1826,
        1835,   68321,    6206,    1656,    1742,    2119,
       68480,    1913,    2024,    1838,   68497,    1670,
        2116,    1824,    2009,    1585,    1586,    1671,
        1896,    1674,    1686,    6251,    1695,    6177,
        1701,   68490,    1658,    1827,    1715,    6185,
        6193,    6211,    1703,    1878,    2122,    1876,
        6223,    1664,    2224,    6245,    1727,    1677,
        1890,    1538,    2124,    2135,    1577,    1791,
        6305,    6273,    1814,    1775,    1569,    1682,
        1808,    1708,    1684,    1774,    6259,    1676,
        1836,    1884,    1610,   68291,    1590,    6239,
        1589,    1587,    1887,    1831,    6238,    6298,
        1747,    1680,    1907,    1685,    1678,    1998,
        6233,    1740,    1899,    6296,    1874,    1888,
        6219,    2217,    1738,    6192,   68495,    1819,
        1718,    1672,    1729,    1544,    6234,    6222,
        1829,   68300,   68305,    1725,    1911,    6241,
        2213,    1649,    1683,    1903,    1666,    1880,
        6178,    1594,   68288,    1745,    1570,    1743,
        1697,   68333,    1687,    1912,    1700,    2223,
        1709,    1730,    6186,    1898,    1722,    1599,
        2208,    6195,    6292,    1872,    1910,    6288,
        6247,    1591,    6257,    2025,    1660,    1653,
        6179,    2132,   68320,    1786,    6207,    6299,
        1608,    2026,   68307,    1568,    2022,    2114,
        1691,    2018,    1813,    6197,    1605,    2112,
        6227,    1749,    2016,    2020,    1707,   68301,
        6196,    6189,    6294,    1711,    2127,    8296,
        1574,    6204,    1710,    2129,    1604,   68298,
        1732,    1572,    1723,    2226,    1821,    1673,
       68324,    6230,    6180,    2042,    1744,    1726,
        1647,    1815,   68311,    1916,    6200,    1679,
       68525,    1919,   68314,   68331,    1573,    6225,
        2130,    1584,    1596,    1603,    6297,    1665,
        6250,    1731,    1828,    1540,    1668,    1900,
        2002,    6187,    1882,    1881,    1901,    6284,
        6262,    6203,    2225,    6158,    6275,   68334,
        1886,    6289,    6214,    1918,    1830,    1659,
        2136,    1879,    2001,    6232,    2131,    1690,
        1693,    6190,    6235,    1728,    1788,   68323,
        6306,    1994,    6309,    2006,    6278,    1652,
        2000,    1704,   68335,    1696,    6212,    6258,
        1579,    1891,    2211,    6213,    1705,    1600,
        1820,    2014,    1607,   68489,   68315,    6236,
        6274,    6280,    2209,    2005,    1595,    6261,
       68494,    1692,   68297,    2126,    2021,    6188,
        2007,    2134,    6283,    2115,    2004,   68310,
        1825,    6263,    6249,    1837,    1832,    2010,
       68296,    6198,    6240,    1606,   68299,   68295,
        6231,    2220,    6248,    6287,    1746,   68526,
        1581,    1893,    6310,    6184,    1541,    2227,
        6255,    1816,   68302,    1721,    6300,    1720,
        2121,    1597,    1539,    6208,   68488,    6311,
        6293,   68486,    2117,   68483,    1602,    6301,
        1662,    1663,    6312,   68306,    1904,    1995,
        6216,    6215,    6282,    1580,    2215,    1655,
        6210,    1646,    1873,    1895,    6256,    1822,
        1897,    6209,    1536,    6277,    6176,   68289,
        1669,    6272,    6221,    1712,   68313,    6201,
       68492,    2125,    1576,    1654,    2214,    1675,
        8205,    6295,    6276,    2133,    1547,   68522,
        1889,    6218,    6286,   68290,    6253,    1870,
        1817,    2210,   68318,    6229,    1593,   68292,
        1583,    6252,    6285,    6150,    6302,    1733,
       68487,    2013,    6254,    6291,   68304,    6202,
        1688,    6182,    6191,   68293,    1737,    2012,
        1906,   68319,   68481,    1905,   68308,   68484,
        1877,    1735,   68523,    1741,    1812,   68316,
        1996,    1885,    1823,    6260,    1694,    2228,
        1810,    1902,    1739,   68482,    6151,    2128,
        6304,   68332,    6242,    6303,    1714,    1661,
        8297,   68527,    6199,    2113,    1871,   68493,
        6290,   68322,    1681,    1717,    2123,    6181,
        6224,   68496,    6226,    1689,    1698,    6243,
        6183,   68524,    6228,   68303,    6307,    2218,
        2212,   68312,
};

uint32_t hz_ucd_arabic_joining_data[524] = {
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI LHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI ZHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WAVY HAMZA BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE PA */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SANAH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DIGIT FOUR ABOVE */
    HZ_JOINING_TYPE_D, /* NKO LA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN THAMEDH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HETH << 6), /* HETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* NKO OO */
    HZ_JOINING_TYPE_D, /* NKO MA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE GA */
    HZ_JOINING_TYPE_D, /* NKO BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* FEH WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* FEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* NKO NYA WOLOSO */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI KA */
    HZ_JOINING_TYPE_U, /* LOW ALEF */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH BAR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* PERSIAN DHALATH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WAVY HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC ATT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* GAMAL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_C, /* MONGOLIAN NIRUGU */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* ARABIC END OF AYAH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH V ABOVE */
    HZ_JOINING_TYPE_U, /* MANICHAEAN HE */
    HZ_JOINING_TYPE_D, /* NKO E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAPH << 6), /* QAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BURUSHASKI << 6), /* BURUSHASKI YEH BARREE WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI ONE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO UE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BURUSHASKI << 6), /* BURUSHASKI YEH BARREE WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D, /* NKO NA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ZHAIN << 6), /* SOGDIAN ZHAIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R, /* MANDAIC AZ */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DOT WITHIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN SADHE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* RISH */
    HZ_JOINING_TYPE_D, /* NKO DA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SWASH << 6), /* SWASH KAF */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO PA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI A */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH ALEF ABOVE */
    HZ_JOINING_TYPE_D, /* NKO SA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NUN << 6), /* NUN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SHIN << 6), /* SHIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN RESH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN HAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* HIGH HAMZA DOTLESS YEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH V ABOVE */
    HZ_JOINING_TYPE_R, /* MANDAIC IT */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI ALEPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D, /* NKO JONA JA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* PERSIAN GHAMAL */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI TAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MANDAIC AH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAMADH << 6), /* LAMADH */
    HZ_JOINING_TYPE_D, /* NKO RA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 4 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT BELOW AND DOT WITHIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE FA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN E */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI LAMEDH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEMKATH << 6), /* SEMKATH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ANG */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO LONG VOWEL SIGN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AK */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 2 DOTS BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO MA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 4 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH STROKE BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE HA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH DOT ABOVE */
    HZ_JOINING_TYPE_U, /* ARABIC FOOTNOTE MARKER */
    HZ_JOINING_TYPE_D, /* MANDAIC AM */
    HZ_JOINING_TYPE_U, /* MANDAIC KAD */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* TEH MARBUTA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KNOTTED << 6), /* KNOTTED HEH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI DHA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI VISARGA ONE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* DOTLESS DALATH RISH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_U, /* HAMZA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH V ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALAPH << 6), /* ALAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU I */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TAW << 6), /* TAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN GIMEL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE IY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_REVERSED << 6), /* REVERSED PE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE I */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI GHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH BARREE WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH V BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* NKO U */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO HAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ALI GALI TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI SADHE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TETH << 6), /* TETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH DOT ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH GOAL */
    HZ_JOINING_TYPE_U, /* ARABIC RAY */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO JIA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO GA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_E << 6), /* E */
    HZ_JOINING_TYPE_U, /* MANICHAEAN JAYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NYA << 6), /* NYA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH DIGIT FOUR BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE U */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* QAF WITH DOT BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH WASLA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH AND 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ALEPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH MADDA ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TEN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DIGIT TWO ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH GOAL WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN BA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH BAR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* DOTLESS NOON */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH V BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN DA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI SSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH HORIZONTAL 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH DIGIT THREE ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE SHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE CHA */
    HZ_JOINING_TYPE_D, /* NKO JONA CHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH ATTACHED RING BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* HIGH HAMZA ALEF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN O */
    HZ_JOINING_TYPE_R, /* MANDAIC ASH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DOT BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZRA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI NGA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW */
    HZ_JOINING_TYPE_D, /* NKO JONA RA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN LAMEDH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH SEPARATE RING BELOW */
    HZ_JOINING_TYPE_D, /* NKO YA */
    HZ_JOINING_TYPE_D, /* MANDAIC AG */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* NKO NYA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DALATH << 6), /* DALATH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN JA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM */
    HZ_JOINING_TYPE_R, /* MANDAIC HALQA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO JA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* DOTLESS TEH MARBUTA */
    HZ_JOINING_TYPE_D, /* NKO NA WOLOSO */
    HZ_JOINING_TYPE_D, /* NKO HA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_L | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN HETH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN CHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN GA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI ZA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF */
    HZ_JOINING_TYPE_D, /* MANDAIC IN */
    HZ_JOINING_TYPE_U, /* FIRST STRONG ISOLATE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MANDAIC ASZ */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ZAYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH ATTACHED RING WITHIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* DOTLESS NOON WITH TAH ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH DOT AND INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YUDH << 6), /* YUDH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TAW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO WA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN U */
    HZ_JOINING_TYPE_C, /* NKO LAJANYALAN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_YEH << 6), /* DOTLESS YEH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KNOTTED << 6), /* KNOTTED HEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_HE << 6), /* HE */
    HZ_JOINING_TYPE_L | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN NUN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DIGIT FOUR BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN WA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI TEN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN AYIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ONE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ALEF << 6), /* ALEF WITH HAMZA BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO DA */
    HZ_JOINING_TYPE_D, /* MANDAIC AQ */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ALI GALI ZHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE JA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* TEH MARBUTA GOAL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FINAL << 6), /* FINAL SEMKATH */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SAMVAT */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* NKO N */
    HZ_JOINING_TYPE_D, /* MONGOLIAN PA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH INVERTED V BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH VERTICAL 2 DOTS BELOW AND TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH VERTICAL 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TTA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU FA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN KHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_STRAIGHT << 6), /* STRAIGHT WAW */
    HZ_JOINING_TYPE_U, /* MONGOLIAN VOWEL SEPARATOR */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI UBADAMA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TWENTY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI DA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO O */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_PE << 6), /* PE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH VERTICAL 2 DOTS BELOW */
    HZ_JOINING_TYPE_U, /* MANDAIC AIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* NKO DAGBASINNA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO GAA */
    HZ_JOINING_TYPE_D, /* MANDAIC AR */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO NIA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_TEH << 6), /* DOTLESS TEH MARBUTA WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH DOT BELOW AND DOT ABOVE */
    HZ_JOINING_TYPE_U, /* MANICHAEAN SHIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI SSA */
    HZ_JOINING_TYPE_D, /* NKO A */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI ZA */
    HZ_JOINING_TYPE_D, /* NKO JA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI THREE BALUDA */
    HZ_JOINING_TYPE_U, /* HIGH HAMZA */
    HZ_JOINING_TYPE_D, /* NKO O */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* DOTLESS QAF WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN HUNDRED */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO E */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ZHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TAH << 6), /* TAH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH */
    HZ_JOINING_TYPE_C, /* TATWEEL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_TETH << 6), /* TETH GARSHUNI */
    HZ_JOINING_TYPE_D, /* NKO KA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HEH << 6), /* HEH */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI KAPH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN PE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO DZA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI DAMARU */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH HAMZA ABOVE */
    HZ_JOINING_TYPE_D, /* NKO TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* KEHEH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU RA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI PE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 3 DOTS BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN ZAYIN */
    HZ_JOINING_TYPE_D, /* MANDAIC AS */
    HZ_JOINING_TYPE_D, /* NKO WA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN QA */
    HZ_JOINING_TYPE_D, /* NKO CHA */
    HZ_JOINING_TYPE_U, /* MANDAIC DUSHENNA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI CA */
    HZ_JOINING_TYPE_D, /* MANDAIC AD */
    HZ_JOINING_TYPE_D, /* NKO PA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN MEM */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MIM << 6), /* MIM */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ZHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE DA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BETH << 6), /* PERSIAN BHETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_SADHE << 6), /* SADHE */
    HZ_JOINING_TYPE_D, /* NKO RRA */
    HZ_JOINING_TYPE_U, /* MANICHAEAN UD */
    HZ_JOINING_TYPE_D, /* MONGOLIAN YA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE UE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON */
    HZ_JOINING_TYPE_U, /* MANICHAEAN JAYIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN WAW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO KA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ROHINGYA << 6), /* ROHINGYA YEH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE TA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI NNA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH BARREE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI TWENTY */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI HALF U */
    HZ_JOINING_TYPE_D, /* MONGOLIAN NA */
    HZ_JOINING_TYPE_U, /* ARABIC NUMBER MARK ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ZA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_SYRIAC << 6), /* WAW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN TETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI CA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_R, /* MANDAIC AKSA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FARSI << 6), /* FARSI YEH WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_U, /* ARABIC SIGN SAFHA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN LHA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI YODH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI HALF YA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI ZHA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI ZAYIN */
    HZ_JOINING_TYPE_D, /* MANDAIC USHENNA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI DALETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_QAF << 6), /* QAF */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI JHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 3 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI BHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SEEN << 6), /* SEEN WITH 2 DOTS AND TAH ABOVE */
    HZ_JOINING_TYPE_D, /* NKO EE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO OE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO U */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI NGA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MEEM << 6), /* MEEM WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* HIGH HAMZA WAW WITH DAMMA ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN CHI */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE RAA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YUDH << 6), /* YUDH HE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_NOON << 6), /* NOON WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ZHI */
    HZ_JOINING_TYPE_U, /* ARABIC NUMBER SIGN */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI BALUDA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN A */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN BETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI ANUSVARA ONE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO QA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN AYIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN FA */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI NUN */
    HZ_JOINING_TYPE_D, /* MANDAIC AN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* BEH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* HIGH HAMZA WAW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH DOUBLE BAR */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL WITH DOT BELOW AND TAH ABOVE */
    HZ_JOINING_TYPE_C, /* ZERO WIDTH JOINER */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI AH */
    HZ_JOINING_TYPE_U, /* MONGOLIAN ALI GALI INVERTED UBADAMA */
    HZ_JOINING_TYPE_D, /* MANDAIC AT */
    HZ_JOINING_TYPE_U, /* AFGHANI SIGN */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI TWO */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH INVERTED 3 DOTS BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO ANG */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI DDA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN BETH WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE HAA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KHAPH << 6), /* SOGDIAN KHAPH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_ZAIN << 6), /* ZAIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH DOT BELOW AND 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO YA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN GIMEL WITH ATTACHED RING BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_DAL << 6), /* DAL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE GAA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI TTHA */
    HZ_JOINING_TYPE_U, /* MONGOLIAN TODO SOFT HYPHEN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI TTA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH BAR */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI HETH */
    HZ_JOINING_TYPE_D, /* NKO FA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE TSA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI PHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN KAPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN KA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN UE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN LA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN DALETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH INVERTED V ABOVE */
    HZ_JOINING_TYPE_D, /* NKO GBA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN QOPH WITH DOT ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI BETH */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 2 DOTS AND TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN DHAMEDH */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI HE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED V BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH DAMMA ABOVE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI THREE */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_YEH << 6), /* YEH WITH TAIL */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAMAL << 6), /* GAMAL GARSHUNI */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN PE WITH DOT ABOVE */
    HZ_JOINING_TYPE_D, /* NKO I */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_AIN << 6), /* AIN WITH 2 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAPH << 6), /* KAPH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU KA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_SAD << 6), /* SAD WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_KAF << 6), /* KAF WITH DOT BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BETH << 6), /* BETH */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_HAH << 6), /* HAH WITH TAH BELOW */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_WAW << 6), /* WAW WITH 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI GIMEL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER */
    HZ_JOINING_TYPE_D, /* MANDAIC AP */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI TA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN FIVE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE ANG */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI DDHA */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_GAF << 6), /* GAF WITH 2 DOTS BELOW */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_BEH << 6), /* DOTLESS BEH WITH INVERTED 3 DOTS ABOVE */
    HZ_JOINING_TYPE_U, /* POP DIRECTIONAL ISOLATE */
    HZ_JOINING_TYPE_U, /* PSALTER PAHLAVI HUNDRED */
    HZ_JOINING_TYPE_D, /* MONGOLIAN RA */
    HZ_JOINING_TYPE_D, /* MANDAIC AB */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FE << 6), /* SOGDIAN FE */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI SAMEKH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN ALI GALI PA */
    HZ_JOINING_TYPE_U, /* MANICHAEAN SHIN */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH TAH ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_LAM << 6), /* LAM WITH V ABOVE */
    HZ_JOINING_TYPE_D, /* MANDAIC AL */
    HZ_JOINING_TYPE_D, /* MONGOLIAN OE */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO TA */
    HZ_JOINING_TYPE_D, /* PSALTER PAHLAVI SHIN */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO CHA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH 4 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH DOT BELOW */
    HZ_JOINING_TYPE_D, /* MONGOLIAN SIBE KA */
    HZ_JOINING_TYPE_D, /* MONGOLIAN EE */
    HZ_JOINING_TYPE_R, /* PSALTER PAHLAVI FOUR */
    HZ_JOINING_TYPE_D, /* MONGOLIAN TODO TSA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN YODH */
    HZ_JOINING_TYPE_D, /* MONGOLIAN MANCHU ALI GALI CYA */
    HZ_JOINING_TYPE_R | (HZ_JOINING_GROUP_REH << 6), /* REH WITH LOOP */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_FEH << 6), /* DOTLESS FEH WITH DOT BELOW AND 3 DOTS ABOVE */
    HZ_JOINING_TYPE_D | (HZ_JOINING_GROUP_MANICHAEAN << 6), /* MANICHAEAN SAMEKH */
};

#endif /* HZ_UCD_8_0_0_H */
